apiVersion: networking.k8s.io/v1
kind: Ingress
#Provides metadata like name, namespace, and annotations.
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization, X-Requested-With"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://voting-app.local"
spec:
  #use nginx-ingress installed via helm
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
# when a user visits voting-app.local/api/* k8s routes it to voting-app-backend-service on port 8080
        paths:
          - path: {{ .Values.ingress.backendPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-backend-service
                port:
                  number: 8080
# when a user visits voting-app.local/ k8s routes it to voting-app-frontend-service on port 80 served by nginx
          - path: {{ .Values.ingress.frontendPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-frontend-service
                port:
                  number: 80
